/** Latin brand/model names — no Hangul/CJK in the catalog UI. */

const BRANDS: Record<string, string> = {
  현대: "Hyundai",
  기아: "Kia",
  제네시스: "Genesis",
  쌍용: "KG Mobility",
  르노코리아: "Renault Korea",
  쉐보레: "Chevrolet",
  삼성: "Renault Samsung",
  벤츠: "Mercedes-Benz",
  아우디: "Audi",
  폭스바겐: "Volkswagen",
  도요타: "Toyota",
  렉서스: "Lexus",
  혼다: "Honda",
  닛산: "Nissan",
  볼보: "Volvo",
  미니: "MINI",
  포르쉐: "Porsche",
  랜드로버: "Land Rover",
  지프: "Jeep",
  테슬라: "Tesla",
  포드: "Ford",
  재규어: "Jaguar",
  링컨: "Lincoln",
  캐딜락: "Cadillac",
  마세라티: "Maserati",
  페라리: "Ferrari",
  람보르기니: "Lamborghini",
  벤틀리: "Bentley",
  롤스로이스: "Rolls-Royce",
  인피니티: "Infiniti",
  미쓰비시: "Mitsubishi",
  스바루: "Subaru",
  마쯔다: "Mazda",
  마즈다: "Mazda",
  푸조: "Peugeot",
  시트로엥: "Citroen",
  폴스타: "Polestar",
  일론: "Tesla",
  日产: "Nissan",
  丰田: "Toyota",
  本田: "Honda",
  大众: "Volkswagen",
  奥迪: "Audi",
  宝马: "BMW",
  奔驰: "Mercedes-Benz",
  保时捷: "Porsche",
  现代: "Hyundai",
  起亚: "Kia",
  吉利: "Geely",
  比亚迪: "BYD",
  长安: "Changan",
  红旗: "Hongqi",
  理想: "Li Auto",
  特斯拉: "Tesla",
  福特: "Ford",
  雪佛兰: "Chevrolet",
  别克: "Buick",
  马自达: "Mazda",
  雷克萨斯: "Lexus",
  沃尔沃: "Volvo",
  凯迪拉克: "Cadillac",
  路虎: "Land Rover",
  捷豹: "Jaguar",
  斯巴鲁: "Subaru",
  三菱: "Mitsubishi",
  名爵: "MG",
  领克: "Lynk & Co",
  小鹏: "XPeng",
  蔚来: "NIO",
  问界: "AITO",
  极氪: "Zeekr",
  哈弗: "Haval",
  长城: "Great Wall",
  荣威: "Roewe",
  五菱: "Wuling",
  奇瑞: "Chery",
  传祺: "Trumpchi",
  广汽: "GAC",
  东风: "Dongfeng",
  奔腾: "Bestune",
  坦克: "Tank",
  深蓝: "Deepal",
  阿维塔: "Avatr",
  智己: "IM Motors",
  零跑: "Leapmotor",
  哪吒: "Neta",
  极狐: "Arcfox",
  腾势: "Denza",
  方程豹: "Yangwang",
  仰望: "Yangwang",
  银河: "Geely Galaxy",
  岚图: "Voyah",
  飞凡: "Rising Auto",
  智界: "Luxeed",
  享界: "Stelato",
  尚界: "Shangjie",
  合创: "Hyptec",
  高合: "HiPhi",
  威马: "WM Motor",
  一汽: "FAW",
  上汽: "SAIC",
  北汽: "BAIC",
  江淮: "JAC",
  东南: "Soueast",
  中华: "Brilliance",
  宝沃: "Borgward",
  斯柯达: "Skoda",
  雪铁龙: "Citroen",
  标致: "Peugeot",
  欧宝: "Opel",
  菲亚特: "Fiat",
  阿尔法罗密欧: "Alfa Romeo",
  阿斯顿马丁: "Aston Martin",
  迈凯伦: "McLaren",
  劳斯莱斯: "Rolls-Royce",
  宾利: "Bentley",
  玛莎拉蒂: "Maserati",
  捷尼赛思: "Genesis",
};

const MODELS: Record<string, string> = {
  팰리세이드: "Palisade",
  쏘렌토: "Sorento",
  스포티지: "Sportage",
  아반떼: "Avante",
  쏘나타: "Sonata",
  그랜저: "Grandeur",
  투싼: "Tucson",
  싼타페: "Santa Fe",
  카니발: "Carnival",
  스타리아: "Staria",
  아이오닉: "Ioniq",
  코나: "Kona",
  베뉴: "Venue",
  캐스퍼: "Casper",
  포터: "Porter",
  봉고: "Bongo",
  렉스턴: "Rexton",
  티볼리: "Tivoli",
  코란도: "Korando",
  토레스: "Torres",
  천래: "Teana",
  天籁: "Teana",
  轩逸: "Sylphy",
  奇骏: "X-Trail",
  途观: "Tiguan",
  途昂: "Teramont",
  探岳: "Tayron",
  帕萨特: "Passat",
  迈腾: "Magotan",
  朗逸: "Lavida",
  速腾: "Sagitar",
  宝来: "Bora",
  汉: "Han",
  秦: "Qin",
  宋: "Song",
  唐: "Tang",
  元: "Yuan",
  海豹: "Seal",
  海豚: "Dolphin",
  驱逐舰: "Destroyer",
  凯美瑞: "Camry",
  卡罗拉: "Corolla",
  雷凌: "Levin",
  荣放: "RAV4",
  汉兰达: "Highlander",
  亚洲龙: "Avalon",
  雅阁: "Accord",
  思域: "Civic",
  飞度: "Fit",
  奥德赛: "Odyssey",
  冠道: "Avancier",
  皓影: "CR-V",
  途岳: "Tharu",
  探歌: "T-Roc",
  高尔夫: "Golf",
  迈巴赫: "Maybach",
  奔驰: "Mercedes-Benz",
  宝马: "BMW",
  奥迪: "Audi",
  理想: "Li",
  小鹏: "XPeng",
  蔚来: "NIO",
  问界: "AITO",
  极氪: "Zeekr",
  红旗: "Hongqi",
  长安: "Changan",
  哈弗: "Haval",
  坦克: "Tank",
  传祺: "Trumpchi",
  领克: "Lynk",
  星越: "Xingyue",
  博越: "Boyue",
  帝豪: "Emgrand",
  缤瑞: "Binrui",
  影豹: "Emkoo",
   UNI: "UNI",
};

const CJK = /[\u1100-\u11FF\u3040-\u30FF\u3400-\u9FFF\uAC00-\uD7AF\uF900-\uFAFF]/g;

export function stripCjk(input: string) {
  return String(input || "")
    .replace(CJK, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function latinBrand(raw: string) {
  const key = String(raw || "").trim();
  if (BRANDS[key]) return BRANDS[key];
  for (const [k, v] of Object.entries(BRANDS)) {
    if (key.includes(k)) return v;
  }
  const latin = stripCjk(key);
  return latin || "Unknown";
}

export function latinModel(raw: string, fallback = "") {
  const key = String(raw || "").trim();
  if (MODELS[key]) return MODELS[key];
  for (const [k, v] of Object.entries(MODELS)) {
    if (k.length >= 2 && key.includes(k)) return v;
  }
  const latin = stripCjk(key);
  if (latin) return latin;
  const fb = stripCjk(fallback);
  return fb || "";
}

export function latinizeVehicle(brand: string, model: string, extra = "") {
  return {
    brand: latinBrand(brand),
    model: latinModel(model, extra) || latinModel(extra) || "",
  };
}
